# Generated by Django 5.1.4 on 2024-12-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=200)),
                ('a', models.TextField(max_length=50)),
                ('b', models.TextField(max_length=50)),
                ('c', models.TextField(max_length=50)),
                ('d', models.TextField(max_length=50)),
            ],
        ),
    ]
